### ISSUE TITLE
a weird issue with brushes on de_nuke from Counter-Strike Source.

### ISSUE THREAD

**Issue by filiperino** [ata4/bspsrc#99] opened 2020-04-23 19:31 UTC
I wanted to request a bugfix for this ongoing issue on de_nuke. Seems to be brush-related and it's definitely something with bspsrc.

Here's how the .vmf looks in Hammer and blender using a 3rd party importer: https://i.imgur.com/W0MrBAN.jpg
https://i.imgur.com/uTI9vYy.jpg

The .vmf extracted with default settings + Smart extracting enabled:
[de_nuke_d.zip](https://github.com/ata4/bspsrc/files/4524781/de_nuke_d.zip)

**Comment by rihi** [comment] 2020-04-23 20:55
Can you give a screenshot of how its supposed to look?
I don't have css but maybe i can still figure whats going there.

**Comment by filiperino** [comment] 2020-04-23 23:03
Sure, here's the map in blender after deleting the broken brushes manually and a couple in-game screens:
https://i.imgur.com/6DR4vLD.jpg
https://i.imgur.com/iZfbkY0.png
https://i.imgur.com/a7XQeAB.png

**Comment by rihi** [comment] 2020-04-23 23:31
Hmm, yeah that's kinda weird.
Just from the images you supplied, it seems like some tool brushes, especially player/clips, were converted to different textures. This shouldn't really happen though.
I'm gonna look into this, maybe I can find the cause.

**Comment by filiperino** [comment] 2020-10-16 06:16
Hi, any progress on this the past few months?

**Comment by rihi** [comment] 2020-10-16 23:55
Yes, sorry for not responding to you sooner.
I did figure what was causing the issue but didn't immediately come around to implementing any proper solution for it. In general I wasn't working much on bspsrc at that time.
Lately however, I started doing some stuff again, including a fix for this issue.
If everything works out, I may already have a fix ready in the next week or so.

**Comment by filiperino** [comment] 2021-04-27 07:38
Any news on pushing this PR to master?

**Closed** 2021-08-02 18:59 UTC
