### ISSUE TITLE
Error I received while decompiling a map called gm_litecity

### ISSUE THREAD

**Issue by Ruskiius** [ata4/bspsrc#104] opened 2020-07-06 08:06 UTC
`[error] BspSource: Can't load C:\Users\(myname)\OneDrive\Desktop\litecity\litecity_b13.bsp, caused by info.ata4.bsplib.BspException: Unknown file ident: 340808514 (BSP)
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:286)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
`

**Comment by Ruskiius** [comment] 2020-07-06 21:26
I got this when I tried to decompile a different map too. `[error] BspSource: Can't load C:\Users\willi\OneDrive\Desktop\locality\locality.bsp, caused by info.ata4.bsplib.BspException: Unknown file ident: 340808514 (BSP)
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:286)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
`

**Comment by rihi** [comment] 2020-08-03 17:27
As far as I know this is an issue with third party gmad extractors. The file is missing its first byte.
Either open the map in a texteditor and ad a 'V' at the beging or extract the gma again but with the `gmad.exe` bundled with garrysmod.

**Comment by Ruskiius** [comment] 2020-08-05 01:50
Okay, thank you. I will try that.

**Comment by rihi** [comment] 2021-11-26 00:40
I'm closing this issue, as it seems to have been caused by a third party rather than bspsrc.
If you still have problems, feel free to comment and I'll have another look at the problem.

**Closed by rihi** 2021-11-26 00:40 UTC
