### ISSUE TITLE
materials that have a i letter in it are replaced by ?

### ISSUE THREAD

**Issue by Fronkln** [ata4/bspsrc#51] opened 2018-09-06 07:34 UTC
Because of this you get missing textures in hammer

**Comment by BlackShadow** [comment] 2019-07-04 12:01
Bumping this.

**Comment by gitRihi** [comment] 2019-09-26 01:44
Can anyone share a bsp where this problem occurs?
I could have a look at it and try to figure out whats going on.

**Comment by Fronkln** [comment] 2019-09-26 14:30
@gitRihi Happens to all BSP's

**Comment by gitRihi** [comment] 2019-09-27 02:51
Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> materials that have 'i' letter in it are replaced by '?'

**Comment by Fronkln** [comment] 2019-09-28 08:34
> Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> 
> > materials that have 'i' letter in it are replaced by '?'

its probably related to language/culture of the computer

**Comment by BlackShadow** [comment] 2019-09-28 11:44
> > Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> > > materials that have 'i' letter in it are replaced by '?'
> 
> its probably related to language/culture of the computer

This may be the issue, because i can't no longer re-produce this issue, because i've added English keyboard. Still this issue should be fixed.

**Comment by gitRihi** [comment] 2019-09-28 14:08
Ohhh, so it's about special characters like `î` in custom material names, that are converted to `?`?

**Comment by Fronkln** [comment] 2019-09-28 14:09
Nah, it can sometimes be related to parsing, for example on C# (even though this is java) stuff like converting strings to lowercase causes i's to turn into ı's this could be a similiar case with this program here

**Comment by gitRihi** [comment] 2019-09-28 21:37
Huh, seems like i learned something new. [The issue seems to be how the turkish language handles the uppercase/lowercase i](http://www.i18nguy.com/unicode/turkish-i18n.html).
The fix should be simple.

**Comment by Fronkln** [comment] 2019-09-29 07:07
yep, exactly what i said earlier

**Closed** 2019-09-29 14:29 UTC
