### ISSUE TITLE
Implement `m_FlagsEx` from CS:GO's static props

### ISSUE THREAD

**Issue by PiMoNFeeD** [ata4/bspsrc#190] opened 2024-09-06 13:38 UTC
It is used for disabling shadow depth and enabling light bounces. You mentioned in README that it is lost on compilation but in fact it isn't; I just made a test map with some props having enabled static prop bounced lighting and some not, and having manually implemented `m_FlagsEx` the output is correct. In fact the entire `m_FlagsEx` field is saved in the BSP file, although there is absolutely no condition in tools to toggle `STATIC_PROP_FLAGS_EX_DISABLE_CSM`, so you can skip that one.

**Comment by SirYodaJedi** [comment] 2024-09-19 01:40
I think this is covered by #102.

**Comment by PiMoNFeeD** [comment] 2024-09-19 10:22
Yeah looks like it, but doesn't seem that it's gonna get any attention

**Comment by rihi** [comment] 2024-09-30 21:11
Thanks for reporting. This is indeed a duplicate of #102, which is now fixed.

**Closed by rihi** 2024-09-30 21:11 UTC
